const ingredientes = [
    '🥕 Zanahoria', 
    '🧅 Cebolla', 
    '🍅 Tomate', 
    '🥩 Carne', 
    '🥓 Tocino', 
    '🍆 Berenjena', 
    '🍗 Pollo', 
    '🌽 Maíz', 
    '🥛 Leche', 
    '🍝 Pasta', 
    '🧀 Queso', 
    '🍟 Papas', 
    '🐟 Pescado', 
    '🌿 Espinaca', 
    '🥑 Aguacate', 
    '🥬 Lechuga', 
    '🍋 Limón',
    '🍳 Huevo',
    '🍞 Pan',
    '🍌 Banano',
    '🍊 Naranja',
    '🧈 Mantequilla',
    '🦐 Camarón',
    '🧄 Ajo',
    '🌶 Pimientos',
    '🍄 Champiñones',
    '🍏 Manzana',
    '🍇 Uva',
    '🥝 Kiwi'
    ];
export default ingredientes;